# Generated by Django 2.0.3 on 2018-11-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181119_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='hypervisor_name',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='client',
            name='hypervisor_ready',
            field=models.BooleanField(default=False),
        ),
    ]
