# Generated by Django 2.0.3 on 2018-11-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_auto_20181121_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hypervisor',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
