# Generated by Django 2.2.7 on 2019-11-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_auto_20181202_1129'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='credentialtype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='credentialtype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='credentialtype',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='job',
            name='archive_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_flag',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
        migrations.DeleteModel(
            name='Credential',
        ),
        migrations.DeleteModel(
            name='CredentialType',
        ),
    ]
