# Generated by Django 4.1.7 on 2023-05-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0016_alter_catalog_created_by_alter_catalog_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mark_as_to_update',
            field=models.BooleanField(default=False),
        ),
    ]
