# Generated by Django 5.0.6 on 2024-06-09 12:48

import cyborgbackup.main.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_add_behind_firewall_on_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_env',
            field=cyborgbackup.main.fields.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('waiting', 'Waiting'), ('running', 'Running'), ('successful', 'Successful'), ('failed', 'Failed'), ('error', 'Error'), ('canceled', 'Canceled'), ('starting', 'Starting')], default='new', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobevent',
            name='event_data',
            field=cyborgbackup.main.fields.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ActivityStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('create', 'Entity Created'), ('update', 'Entity Updated'), ('delete', 'Entity Deleted'), ('associate', 'Entity Associated with another Entity'), ('disassociate', 'Entity was Disassociated with another Entity')], max_length=13)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.TextField(blank=True)),
                ('object_relationship_type', models.TextField(blank=True)),
                ('object1', models.TextField()),
                ('object2', models.TextField()),
                ('setting', cyborgbackup.main.fields.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_stream', to=settings.AUTH_USER_MODEL)),
                ('client', models.ManyToManyField(blank=True, to='main.client')),
                ('job', models.ManyToManyField(blank=True, to='main.job')),
                ('policy', models.ManyToManyField(blank=True, to='main.policy')),
                ('repository', models.ManyToManyField(blank=True, to='main.repository')),
                ('schedule', models.ManyToManyField(blank=True, to='main.schedule')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
