# Generated by Django 4.1.7 on 2024-11-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_user_is_staff_alter_job_job_env_alter_job_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='partitioning',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
