# Generated by Django 2.0.3 on 2018-12-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0005_job_pruned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_backup_daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_backup_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_backup_monthly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_backup_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_backup_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_backup_weekly',
            field=models.BooleanField(default=False),
        ),
    ]
