# Generated by Django 2.2.12 on 2020-04-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0008_alter_policytype_20191225_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='posthook',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='policy',
            name='prehook',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
