# Generated by Django 2.2.17 on 2021-01-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_client_bandwidth_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='group',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='order',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('job', 'Default Backup Job'), ('check', 'Prepare Client or Repository'), ('catalog', 'Catalog Job'), ('prune', 'Prune Job'), ('restore', 'Restore Job')], default='job', max_length=64),
        ),
        migrations.AlterField(
            model_name='policy',
            name='clients',
            field=models.ManyToManyField(blank=True, to='main.Client'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('rootfs', 'Root FileSystem'), ('vm', 'Virtual Machine'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('piped', 'Piped Backup'), ('config', 'Only /etc'), ('mail', 'Only mail directory'), ('folders', 'Specified folders'), ('proxmox', 'Proxmox')], default='rootfs', max_length=20),
        ),
    ]
