# Generated by Django 2.2.19 on 2021-05-14 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210115_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='master_job',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_master_job+', to='main.Job'),
        ),
    ]
