# Generated by Django 2.2.19 on 2021-05-14 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0012_job_master_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='port',
            field=models.PositiveIntegerField(blank=True, default=22, max_length=5,
                                              validators=[django.core.validators.MinValueValidator(1),
                                                          django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
